#!/usr/bin/env bash
# JankyBorders config - generated by theme system
# Theme: {{ name }}

hex_to_argb() { echo "${1/#\#/0xff}"; }

options=(
  style=round
  width=6
  active_color="glow($(hex_to_argb '{{ accent }}'))"
  inactive_color=$(hex_to_argb '{{ ui_border_secondary }}')
  hidpi=on
)

borders "${options[@]}"
