{
  "$schema": "https://opencode.ai/theme.json",
  "theme": {
    "primary": "{{ accent }}",
    "secondary": "{{ color4 }}",
    "accent": "{{ color5 }}",
    "error": "{{ color1 }}",
    "warning": "{{ color3 }}",
    "success": "{{ color2 }}",
    "info": "{{ color6 }}",
    "text": "{{ foreground }}",
    "textMuted": "{{ ui_gray }}",
    "background": "{{ background }}",
    "backgroundPanel": "{{ background }}",
    "backgroundElement": "{{ ui_border_faint }}",
    "border": "{{ ui_border_secondary }}",
    "borderActive": "{{ ui_border }}",
    "borderSubtle": "{{ ui_border_faint }}",
    "diffAdded": "{{ color2 }}",
    "diffRemoved": "{{ color1 }}",
    "diffContext": "{{ color8 }}",
    "diffHunkHeader": "{{ color8 }}",
    "diffHighlightAdded": "{{ color10 }}",
    "diffHighlightRemoved": "{{ color9 }}",
    "diffAddedBg": "{{ ui_border_faint }}",
    "diffRemovedBg": "{{ ui_border_faint }}",
    "diffContextBg": "{{ background }}",
    "diffLineNumber": "{{ ui_gray }}",
    "diffAddedLineNumberBg": "{{ ui_border_faint }}",
    "diffRemovedLineNumberBg": "{{ ui_border_faint }}",
    "markdownText": "{{ foreground }}",
    "markdownHeading": "{{ accent }}",
    "markdownLink": "{{ color4 }}",
    "markdownLinkText": "{{ color6 }}",
    "markdownCode": "{{ color2 }}",
    "markdownBlockQuote": "{{ color8 }}",
    "markdownEmph": "{{ color3 }}",
    "markdownStrong": "{{ color5 }}",
    "markdownHorizontalRule": "{{ ui_border_faint }}",
    "markdownListItem": "{{ accent }}",
    "markdownListEnumeration": "{{ color6 }}",
    "markdownImage": "{{ color4 }}",
    "markdownImageText": "{{ color6 }}",
    "markdownCodeBlock": "{{ foreground }}",
    "syntaxComment": "{{ color8 }}",
    "syntaxKeyword": "{{ color5 }}",
    "syntaxFunction": "{{ color4 }}",
    "syntaxVariable": "{{ color6 }}",
    "syntaxString": "{{ color2 }}",
    "syntaxNumber": "{{ color3 }}",
    "syntaxType": "{{ color6 }}",
    "syntaxOperator": "{{ color5 }}",
    "syntaxPunctuation": "{{ foreground }}"
  }
}
