#!/bin/bash
# SketchyBar colors - generated by theme system
# Theme: {{ name }}

# Helper to convert #RRGGBB to 0xAARRGGBB
hex_to_argb() { echo "${1/#\#/0xff}"; }
hex_to_argb_alpha() { echo "0x$1${2/#\#/}"; }

# Bar appearance
export BAR_COLOR=$(hex_to_argb_alpha cc "{{ background }}")  # Semi-transparent bg
export ITEM_BG_COLOR=0x00000000

# Theme colors
export ACCENT_COLOR=$(hex_to_argb "{{ accent }}")
export FOREGROUND=$(hex_to_argb "{{ foreground }}")
export FOREGROUND_DIM=$(hex_to_argb "{{ ui_gray }}")
export BACKGROUND=$(hex_to_argb "{{ background }}")

# Palette
export RED=$(hex_to_argb "{{ color1 }}")
export GREEN=$(hex_to_argb "{{ color2 }}")
export YELLOW=$(hex_to_argb "{{ color3 }}")
export BLUE=$(hex_to_argb "{{ color4 }}")
export MAGENTA=$(hex_to_argb "{{ color5 }}")
export CYAN=$(hex_to_argb "{{ color6 }}")
export WHITE=$(hex_to_argb "{{ color7 }}")
