# {{ name }} theme for tmux

thm_bg="default"
thm_bg_dark="default"
thm_fg="{{ foreground }}"
thm_gray="{{ ui_gray }}"
thm_magenta="{{ color5 }}"
thm_pink="{{ color1 }}"
thm_green="{{ color2 }}"
thm_blue="{{ color4 }}"
thm_black="{{ color0 }}"
thm_yellow="{{ color3 }}"
thm_selected="{{ ui_selected }}"
thm_match="{{ ui_match }}"

set-window-option -g window-active-style "fg=${thm_fg}"
set-window-option -g window-style "fg=${thm_gray}"
set -g status-style 'fg=white'
set -g pane-active-border-style "fg={{ ui_border }}"
set -g pane-border-style "fg={{ ui_border_faint }},bg=default"
set -g popup-border-style "fg={{ ui_gray }},bg=${thm_bg_dark}"
set -g copy-mode-match-style "bg={{ ui_match }}"
set -g copy-mode-current-match-style "fg=${thm_bg_dark},bg=${thm_yellow}"
set -g mode-style "bg=${thm_selected}"
set -g message-style fg="${thm_yellow}",bg="${thm_bg_dark}",align="centre"
set -g message-command-style fg="${thm_blue}",bg="${thm_gray}",align="centre"
setw -g window-status-format "#[fg=${thm_gray}]#I #{?#{e|>:#{window_panes},1}, #{pane_current_command},#W}"
setw -g window-status-current-format "#[fg=${thm_green},bold]#I #{#{?#{e|>:#{window_panes},1}, #{pane_current_command},#W}}"
setw -g window-status-separator "#[fg={{ ui_border }}] | "
set -g status-left "#[fg=#{?client_prefix,${thm_yellow},${thm_fg}},bg=${thm_bg_dark}]#S#[fg=${thm_fg},bg=default] ▸ "
