#!/bin/bash
# SketchyBar colors - generated by theme system
# Theme: Gruvbox Dark

# Helper to convert #RRGGBB to 0xAARRGGBB
hex_to_argb() { echo "${1/#\#/0xff}"; }
hex_to_argb_alpha() { echo "0x$1${2/#\#/}"; }

# Bar appearance
export BAR_COLOR=$(hex_to_argb_alpha cc "#1d2021")  # Semi-transparent bg
export ITEM_BG_COLOR=0x00000000

# Theme colors
export ACCENT_COLOR=$(hex_to_argb "#83a598")
export FOREGROUND=$(hex_to_argb "#ebdbb2")
export FOREGROUND_DIM=$(hex_to_argb "#928374")
export BACKGROUND=$(hex_to_argb "#1d2021")

# Palette
export RED=$(hex_to_argb "#cc241d")
export GREEN=$(hex_to_argb "#98971a")
export YELLOW=$(hex_to_argb "#d79921")
export BLUE=$(hex_to_argb "#458588")
export MAGENTA=$(hex_to_argb "#b16286")
export CYAN=$(hex_to_argb "#689d6a")
export WHITE=$(hex_to_argb "#a89984")
